# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
url: "https://bluescreenofjeff.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: bluescreenofjeff.com - a blog about penetration testing and red teaming

# Short description of your site
description: An information security blog by penetration tester and red teamer Jeff Dimmock.

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  "About" : "about"
  "Posts" : "posts"
  "Tags" : "tags"
  "Talks" : "talks"
  "Twitter" : "https://twitter.com/bluscreenofjeff"
  "GitHub" : "https://github.com/bluscreenofjeff"
  "RSS" : "https://bluescreenofjeff.com/feed.xml"


#Old
#<span class="fa-stack fa-lg" title="GitHub"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-github fa-stack-1x fa-inverse"></i></span> : "https://github.com/bluscreenofjeff"
  #<span class="fa-stack fa-lg" title="Twitter"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-twitter fa-stack-1x fa-inverse"></i></span> : "https://twitter.com/bluscreenofjeff"
  #<span class="fa-stack fa-lg" title="RSS Feed"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-rss fa-stack-1x fa-inverse"></i></span> : "http://bluscreenofjeff.com/feed.xml"
#  <span class="fa-stack fa-lg" title="About"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-user fa-stack-1x fa-inverse"></i></span> : "about"
#  <span class="fa-stack fa-lg" title="Post Archive"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-list-ul fa-stack-1x fa-inverse"></i></span> : "archive"
#  <span class="fa-stack fa-lg" title="Posts by Tag"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-tags fa-stack-1x fa-inverse"></i></span> : "tags"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Jeff Dimmock
  github: bluscreenofjeff
  twitter: bluscreenofjeff

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "bluescreenofjeff.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- SEO --- #

twitter:
  username: bluscreenofjeff

logo: /assets/bsoj.png

social:
  name: Jeff Dimmock
  links:
      - https://twitter.com/bluscreenofjeff
      - https://github.com/bluscreenofjeff
      - https://keybase.io/bluescreenofjeff
      - https://www.linkedin.com/in/jeffdimmock/

image:
  path: /assets/bsoj.png
  height: 300
  width: 300

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "bluescreenofjeff"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-61938642-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Los Angeles"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:{line_numbers: true}
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."


# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
